# fly.toml app configuration file generated for lbrestaurant-website on 2024-01-05T00:34:57+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lbrestaurant-website"
primary_region = "nrt"
console_command = "/rails/bin/rails console"

[build]

[deploy]
  release_command = "./bin/rails db:prepare"

[processes]
  web = "bin/rails server -b 0.0.0.0"
  cron = "supercronic /rails/crontab"

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["web"]

[[vm]]
  processes = ["web"]
  cpu_kind = "shared"
  cpus = 2
  memory = '4gb'

[[vm]]
  processes = ["cron"]
  cpu_kind = "shared"
  cpus = 1
  memory = '256mb'

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
