version: '3'

services:
  postgresdb:
    image: postgres:14.10
    container_name: postgres_container
    environment:
      POSTGRES_DB: lbrestaurant_db
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
