default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: docker
  password: docker
  host: 127.0.0.1
  database: lbrestaurant_db

development:
  <<: *default
  database: lbrestaurant_db

test:
  <<: *default
  database: lbrestaurant_db

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
