default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: docker
  password: docker
  host: localhost
  port: 5432
  database: lbrestaurant_db

development:
  <<: *default
  database: lbrestaurant_db_develop

test:
  <<: *default
  database: lbrestaurant_db_test

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
