default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: docker
  password: docker
  host: 127.0.0.1
  database: my_testdb

development:
  <<: *default
  database: my_testdb_development

test:
  <<: *default
  database: my_testdb_test

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
