# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: docker
  password: docker
  host: mysqldb
  database: my_testdb

development:
  <<: *default
  database: my_testdb_development

test:
  <<: *default
  database: my_testdb_test
